#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80 make it return a page with
# "Hello World" in it
# and Configure your Nginx server so that /redirect_me is
# redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
service nginx restart
