#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
		listen 80 default_server;
	        listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
		if (\$request_filename ~ redirect_me) {
			rewrite ^ https://khennyyb.tech permanent;
		}
	}" > /etc/nginx/sites-available/default
service nginx restart
