#!/usr/bin/env bash
# Script to configure web-02 exactly like web-01

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo -e "Ceci n'est pas une page" > /var/www/html/error-page.html
echo "server {
		listen 80 default_server;
	        listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
		location / {
			try_files \$uri \$uri/ =404;
			add_header X-Served-By \$hostname;
		}
		if (\$request_filename ~ redirect_me) {
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
		}
		error_page 404 /error-page.html;
		location = /error-page.html{
			root /var/www/html;
			internal;
		}
	}" > /etc/nginx/sites-available/default
service nginx restart
