#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  khennyyb-frontend
        bind *:80
        mode http
        default_backend khennyyb-backend
backend khennyyb-backend
        balance roundrobin
        server 25768-web-01 34.204.193.247:80 check
        server 25768-web-02 3.239.48.181:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
