#!/bin/bash
ls -l -rwxr--r-- 1 root root 16 Mar  2 00:26 0-current_working_directory -rwxr-xr-x 1 root root 62 Mar  2 01:04 1-listit  -rwxr-xr-x 1 root root 21 Mar  2 01:23 2-bring_me_home  -rw-r--r-- 1 root root 18 Mar  2 01:41 3-listfiles  -rw-r--r-- 1 root root 38 Mar  1 23:09 README.md
