#!/usr/bin/env bash
#  displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

for ((c=1; c<=100; c++));
	do
	if ((c % 5 == 0)) && ((c % 3 == 0));
		then
		echo "FizzBuzz";
	elif ((c % 3 == 0));
		then
		echo "Fizz";
	elif ((c % 5 == 0));
		then
		echo "Buzz";
	else
		echo $c;
	fi;
done;
