#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
c=1
while [[ $c -le 10 ]];
	do
	echo "Best School"
	if [ $c -eq 9 ];
		then
		echo "Hi";
	fi;
	(( c++ ))
done;
