#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
m=1
h=0
while [[ $h -le 12 ]];
	do
	echo "Hour: "$h
	while [[ $m -le 59 ]];
		do
		echo $m
		(( m++ ));
	done;
	(( m=1 ))
	(( h++ ));
done;
