#!/usr/bin/env bash
# fixing docker container to return a page with text "Hello Holberton"
# the problem is in apache, the service wasn't started

# run the image incase wasn't running
#docker run -p 8080:80 -d -it holbertonschool/265-0

# get the container id
#id=$(docker ps | grep "holbertonschool/265-0" | cut -d' ' -f1)

# start apache service in the container
#docker exec -i "$id" service apache2 start
sudo service apache2 start
