#!/usr/bin/env bash
# Scripts that restarts nginx as nginx user
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80 /8080 /g' /etc/nginx/sites-available/default
pkill -9 apache
chmod +rwx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
